# Generated by Django 4.1.7 on 2023-03-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('published_on', models.DateTimeField()),
                ('author', models.CharField(max_length=44)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish blog')],
            },
        ),
    ]
